# Generated by Django 4.1.3 on 2023-01-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=40)),
                ('Rating', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
