# Generated by Django 4.1.3 on 2023-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrate',
            name='Rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
