# Generated by Django 4.1.3 on 2023-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_addrate_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmoviedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=40)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
    ]
